name: "duphold"
description: SV callers like lumpy look at split-reads and pair distances to find
  structural variants. This tool is a fast way to add depth information to those calls.
  This can be used as additional information for filtering variants; for example we
  will be skeptical of deletion calls that do not have lower than average coverage
  compared to regions with similar gc-content.
keywords:
  - sort
tools:
  - "duphold":
      description: "SV callers like lumpy look at split-reads and pair distances to
        find structural variants. This tool is a fast way to add depth information to
        those calls."
      homepage: "https://github.com/brentp/duphold"
      documentation: "https://github.com/brentp/duphold"
      tool_dev_url: "https://github.com/brentp/duphold"
      doi: "10.1093/gigascience/giz040"
      licence: "['MIT']"
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - alignment_file: {}
    - alignement_index: {}
    - sv_variants:
        type: file
        description: A variants file containing structural variants
        pattern: "*.{vcf,bcf}(.gz)?"
    - snp_variants:
        type: file
        description: A variants file containing SNPs
        pattern: "*.{vcf,bcf}(.gz)?"
    - snp_variants_index: {}
  - - fasta: {}
  - - fasta_fai: {}
output:
  - vcf:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.vcf.gz":
          type: file
          description: The output VCF
          pattern: "*.vcf.gz"
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@nvnieuwk"
maintainers:
  - "@nvnieuwk"
