name: multiqc
description: Aggregate results from bioinformatics analyses across many samples into
  a single report
keywords:
  - QC
  - bioinformatics tools
  - Beautiful stand-alone HTML report
tools:
  - multiqc:
      description: |
        MultiQC searches a given directory for analysis logs and compiles a HTML report.
        It's a general use tool, perfect for summarising the output from numerous bioinformatics tools.
      homepage: https://multiqc.info/
      documentation: https://multiqc.info/docs/
      licence: ["GPL-3.0-or-later"]
      identifier: biotools:multiqc
input:
  - - multiqc_files:
        qualifier: path
        type: file
        description: |
          List of reports / files recognised by MultiQC, for example the html and zip output of FastQC
  - - multiqc_config:
        qualifier: path
        type: file
        description: Optional config yml for MultiQC
        pattern: "*.{yml,yaml}"
  - - extra_multiqc_config:
        qualifier: path
        type: file
        description: Second optional config yml for MultiQC. Will override common sections
          in multiqc_config.
        pattern: "*.{yml,yaml}"
  - - multiqc_logo:
        qualifier: path
        type: file
        description: Optional logo file for MultiQC
        pattern: "*.{png}"
output:
  - report:
      - "*multiqc_report.html":
          qualifier: path
          type: file
          description: MultiQC report file
          pattern: "multiqc_report.html"
  - data:
      - "*_data":
          qualifier: path
          type: directory
          description: MultiQC data dir
          pattern: "multiqc_data"
  - plots:
      - "*_plots":
          qualifier: path
          type: file
          description: Plots created by MultiQC
          pattern: "*_data"
  - versions:
      - versions.yml:
          qualifier: path
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@abhi18av"
  - "@bunop"
  - "@drpatelh"
  - "@jfy133"
maintainers:
  - "@abhi18av"
  - "@bunop"
  - "@drpatelh"
  - "@jfy133"
