name: bwa_mem
description: Performs fastq alignment to a fasta reference using BWA
keywords:
  - mem
  - bwa
  - alignment
  - map
  - fastq
  - bam
  - sam
tools:
  - bwa:
      description: |
        BWA is a software package for mapping DNA sequences against
        a large reference genome, such as the human genome.
      homepage: http://bio-bwa.sourceforge.net/
      documentation: https://bio-bwa.sourceforge.net/bwa.shtml
      arxiv: arXiv:1303.3997
      licence: ["GPL-3.0-or-later"]
      identifier: "biotools:bwa"
input:
  - - meta:
        qualifier: val
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - reads:
        qualifier: path
        type: file
        description: |
          List of input FastQ files of size 1 and 2 for single-end and paired-end data,
          respectively.
  - - meta2:
        qualifier: val
        type: map
        description: |
          Groovy Map containing reference information.
          e.g. [ id:'test', single_end:false ]
    - index:
        qualifier: path
        type: file
        description: BWA genome index files
        pattern: "Directory containing BWA index *.{amb,ann,bwt,pac,sa}"
  - - meta3:
        qualifier: val
        type: map
        description: |
          Groovy Map containing reference information.
          e.g. [ id:'test', single_end:false ]
    - fasta:
        qualifier: path
        type: file
        description: Reference genome in FASTA format
        pattern: "*.{fasta,fa}"
  - - sort_bam:
        qualifier: val
        type: boolean
        description: use samtools sort (true) or samtools view (false)
        pattern: "true or false"
output:
  - bam:
      - meta:
          qualifier: val
          type: file
          description: Output BAM file containing read alignments
          pattern: "*.{bam}"
      - "*.bam":
          qualifier: path
          type: file
          description: Output BAM file containing read alignments
          pattern: "*.{bam}"
  - cram:
      - meta:
          qualifier: val
          type: file
          description: Output CRAM file containing read alignments
          pattern: "*.{cram}"
      - "*.cram":
          qualifier: path
          type: file
          description: Output CRAM file containing read alignments
          pattern: "*.{cram}"
  - csi:
      - meta:
          qualifier: val
          type: file
          description: Optional index file for BAM file
          pattern: "*.{csi}"
      - "*.csi":
          qualifier: path
          type: file
          description: Optional index file for BAM file
          pattern: "*.{csi}"
  - crai:
      - meta:
          qualifier: val
          type: file
          description: Optional index file for CRAM file
          pattern: "*.{crai}"
      - "*.crai":
          qualifier: path
          type: file
          description: Optional index file for CRAM file
          pattern: "*.{crai}"
  - versions:
      - versions.yml:
          qualifier: path
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@drpatelh"
  - "@jeremy1805"
  - "@matthdsm"
maintainers:
  - "@drpatelh"
  - "@jeremy1805"
  - "@matthdsm"
