name: "hlala_typing"
description: Performs HLA typing based on a population reference graph and employs
  a new linear projection method to align reads to the graph.
keywords:
  - hla
  - hlala
  - hla_typing
  - hlala_typing
tools:
  - "hlala":
      description: "HLA typing from short and long reads"
      homepage: "https://github.com/DiltheyLab/HLA-LA"
      documentation: "https://github.com/DiltheyLab/HLA-LA#running-hlala"
      tool_dev_url: "https://github.com/DiltheyLab/HLA-LA"
      doi: "10.1093/bioinformatics/btz235"
      licence: "['GPL']"
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - bam:
        type: file
        description: BAM/CRAM/SAM file
        pattern: "*.{bam,cram,sam}"
    - bai: {}
    - graph:
        type: directory
        description: Path to prepared graph with hla-la --acton prepareGraph
output:
  - results:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - ${meta.id}: {}
  - extraction:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - ${meta.id}/extraction.bam*: {}
  - extraction_mapped:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - ${meta.id}/extraction_mapped.bam: {}
  - extraction_unmpapped:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - ${meta.id}/extraction_unmapped.bam: {}
  - hla:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - ${meta.id}/hla/*: {}
  - fastq:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - ${meta.id}/*.fastq: {}
  - reads_per_level:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - ${meta.id}/reads_per_level.txt: {}
  - remapped:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - ${meta.id}/remapped_with_a.bam*: {}
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@mapo9"
maintainers:
  - "@mapo9"
