name: tabix_bgziptabix
description: bgzip a sorted tab-delimited genome file and then create tabix index
keywords:
  - bgzip
  - compress
  - index
  - tabix
  - vcf
tools:
  - tabix:
      description: Generic indexer for TAB-delimited genome position files.
      homepage: https://www.htslib.org/doc/tabix.html
      documentation: https://www.htslib.org/doc/tabix.1.html
      doi: 10.1093/bioinformatics/btq671
      licence: ["MIT"]
      identifier: biotools:tabix
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - input: {}
output:
  - gz_tbi:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.gz": {}
      - "*.tbi": {}
  - gz_csi:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.gz": {}
      - "*.csi": {}
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@maxulysse"
  - "@DLBPointon"
maintainers:
  - "@maxulysse"
  - "@DLBPointon"
