name: "atlas_splitmerge"
description: split single end read groups by length and merge paired end reads
keywords:
  - split
  - merge
  - bam
  - read group
tools:
  - "atlas":
      description: "ATLAS, a suite of methods to accurately genotype and estimate genetic
        diversity"
      homepage: "https://bitbucket.org/wegmannlab/atlas/wiki/Home"
      documentation: "https://bitbucket.org/wegmannlab/atlas/wiki/Home"
      tool_dev_url: "https://bitbucket.org/wegmannlab/atlas"
      doi: "10.1101/105346"
      licence: "['GPL v3']"
      identifier: biotools:atlas_db
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - bam:
        type: file
        description: Single input BAM file.
        pattern: "*.bam"
    - bai:
        type: file
        description: The BAI file for the input BAM file
        pattern: "*.bai"
    - read_group_settings: {}
    - blacklist:
        type: file
        description: |
          blacklist.txt (optional), A txt file with blacklisted read names
          that should be ignored and just written to file, each on a new line
        pattern: "*.txt"
output:
  - data:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*_mergedReads.bam": {}
      - "*.txt.gz": {}
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@merszym"
maintainers:
  - "@merszym"
