name: "atlas_splitmerge"
description: split single end read groups by length and merge paired end reads
keywords:
  - split
  - merge
  - bam
  - read group
tools:
  - "atlas":
      description: "ATLAS, a suite of methods to accurately genotype and estimate genetic
        diversity"
      homepage: "https://bitbucket.org/wegmannlab/atlas/wiki/Home"
      documentation: "https://bitbucket.org/wegmannlab/atlas/wiki/Home"
      tool_dev_url: "https://bitbucket.org/wegmannlab/atlas"
      doi: "10.1101/105346"
      licence: ["GPL v3"]
      identifier: biotools:atlas_db
input:
  - - meta:
        qualifier: val
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - bam:
        qualifier: path
        type: file
        description: Single input BAM file.
        pattern: "*.bam"
    - bai:
        qualifier: path
        type: file
        description: The BAI file for the input BAM file
        pattern: "*.bai"
    - read_group_settings:
        type: file
        description: |
          TXT file containing the split and merge settings for
          each readgroup. Each line consist of one readgroup,
          single/double identifier and the maximum cycle number
          of the sequencer. e.g. "RG1 single 100"
        pattern: "*.txt"
        qualifier: path
    - blacklist:
        qualifier: path
        type: file
        description: |
          blacklist.txt (optional), A txt file with blacklisted read names
          that should be ignored and just written to file, each on a new line
        pattern: "*.txt"
output:
  - data:
      - meta:
          qualifier: val
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*_mergedReads.bam":
          type: file
          description: A BAM file with suffix_mergedReads.bam
          pattern: "*_mergedReads.bam"
          qualifier: path
      - "*.txt.gz":
          type: file
          description: A file listing all reads that were filtered out in the merging process with suffix_ignoredReads.txt.gz
          pattern: "*.txt.gz"
          qualifier: path
  - versions:
      - versions.yml:
          qualifier: path
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@merszym"
maintainers:
  - "@merszym"
