name: "calder2"
description: Hierarchical Hi-C compartment computation
keywords:
  - calder2
  - genome
  - topology
  - compartments
  - domains
  - hi-c
tools:
  - "calder2":
      description: "Hierarchical Hi-C compartment computation"
      homepage: "https://github.com/CSOgroup/CALDER2"
      documentation: "https://github.com/CSOgroup/CALDER2"
      tool_dev_url: "https://github.com/CSOgroup/CALDER2"
      doi: "10.1038/s41467-021-22666-3"
      licence: ["MIT"]
      identifier: ""
input:
  - - meta:
        type: map
        description: Groovy Map containing sample information. E.g. [ id:'test', single_end:false
          ]
    - cool: {}
  - - resolution:
        type: value
        description: In case a .mcool file is provided, which resolution level to use
          for the analysis
output:
  - output_folder:
      - meta:
          type: map
          description: Groovy Map containing sample information. E.g. [ id:'test', single_end:false
            ]
      - ${meta.id}/: {}
  - intermediate_data_folder:
      - meta:
          type: map
          description: Groovy Map containing sample information. E.g. [ id:'test', single_end:false
            ]
      - ${meta.id}/intermediate_data/: {}
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@lucananni93"
maintainers:
  - "@lucananni93"
