# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: bam_sort_stats_samtools
description: Sort SAM/BAM/CRAM file
keywords:
  - sort
  - bam
  - sam
  - cram
components:
  - samtools/sort
  - samtools/index
  - samtools/stats
  - samtools/idxstats
  - samtools/flagstat
  - bam_stats_samtools

input:
  - ch_bam:
      description: Channel containing a meta map and bam file. Intput to samtools/sort module.
      scructure:
        - meta:
            type: map
            description: Groovy Map containing sample information
        - bam:
            type: file
            description: BAM/CRAM/SAM file
            pattern: "*.{bam,cram,sam}"
  - ch_fasta:
      description: Channel containing a fasta file. Input to samtools/sort module.
      structure:
        - fasta:
            type: file
            description: Reference genome fasta file
            pattern: "*.{fasta,fa}"

output:
  - bam:
      description: Channel containing sorted BAM/CRAM/SAM file. Output from samtools/sort module.
      scructure:
        - meta:
            type: map
            description: |
              Groovy Map containing sample information
              e.g. [ id:'test', single_end:false ]
        - bam:
            type: file
            description: Sorted BAM/CRAM/SAM file
            pattern: "*.{bam,cram,sam}"
  - bai:
      description: Channel containing BAM index file. Output from samtools/index module.
      structure:
        - meta:
            type: map
            description: |
              Groovy Map containing sample information
              e.g. [ id:'test', single_end:false ]
        - bai:
            type: file
            description: BAM index file
            pattern: "*.{bai,crai,sai}"
  - csi:
      description: Channel containing CSI index file. Output from samtools/index module.
      sctructure:
        - meta:
            type: map
            description: |
              Groovy Map containing sample information
              e.g. [ id:'test', single_end:false ]
        - csi:
            type: file
            description: CSI index file
  - stats:
      description: Channel containing BAM stats. Output from samtools/stats module.
      structure:
        - meta:
            type: map
            description: |
              Groovy Map containing sample information
              e.g. [ id:'test', single_end:false ]
        - stats:
            type: file
            description: File containing samtools stats output
            pattern: "*.{stats}"
  - falgstats:
      description: Channel containing BAM flagstat. Output from samtools/stats module.
      structure:
        - meta:
            type: map
            description: |
              Groovy Map containing sample information
              e.g. [ id:'test', single_end:false ]
        - flagstats:
            type: file
            description: File containing samtools flagstat output
            pattern: "*.{flagstat}"
  - idxtats:
      description: Channel containing BAM idxstats. Output from samtools/stats module.
      structure:
        - meta:
            type: map
            description: |
              Groovy Map containing sample information
              e.g. [ id:'test', single_end:false ]
        - idxstats:
            type: file
            description: File containing samtools idxstats output
            pattern: "*.{idxstats}"
  - versions:
      description: Channel containing tools versions YAML file.
      structure:
        - versions:
          type: file
          description: File containing software versions
          pattern: "versions.yml"

authors:
  - "@drpatelh"
  - "@ewels"
maintainers:
  - "@drpatelh"
  - "@ewels"
