name: bcftools_merge
description: Merge VCF files
keywords:
  - variant calling
  - merge
  - VCF
tools:
  - merge:
      description: |
        Merge VCF files.
      homepage: http://samtools.github.io/bcftools/bcftools.html
      documentation: http://www.htslib.org/doc/bcftools.html
      doi: 10.1093/bioinformatics/btp352
      licence: ["MIT"]
      identifier: biotools:bcftools
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - vcfs:
        type: file
        description: |
          List containing 2 or more vcf files
          e.g. [ 'file1.vcf', 'file2.vcf' ]
    - tbis:
        type: file
        description: |
          List containing the tbi index files corresponding to the vcfs input files
          e.g. [ 'file1.vcf.tbi', 'file2.vcf.tbi' ]
  - - meta2:
        type: map
        description: |
          Groovy Map containing reference information
          e.g. [ id:'genome' ]
    - fasta:
        type: file
        description: "(Optional) The fasta reference file (only necessary for the `--gvcf
          FILE` parameter)"
        pattern: "*.{fasta,fa}"
  - - meta3:
        type: map
        description: |
          Groovy Map containing reference information
          e.g. [ id:'genome' ]
    - fai:
        type: file
        description: "(Optional) The fasta reference file index (only necessary for
          the `--gvcf FILE` parameter)"
        pattern: "*.fai"
  - - bed:
        type: file
        description: "(Optional) The bed regions to merge on"
        pattern: "*.bed"
output:
  - merged_variants:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.{bcf,vcf}{,.gz}": {}
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@joseespinosa"
  - "@drpatelh"
  - "@nvnieuwk"
  - "@ramprasadn"
maintainers:
  - "@joseespinosa"
  - "@drpatelh"
  - "@nvnieuwk"
  - "@ramprasadn"
