name: "scimap_mcmicro"
description: SCIMAP is a suite of tools that enables spatial single-cell analyses
keywords:
  - sort
  - spatial
  - single cell
tools:
  - "scimap":
      description: "Scimap is a scalable toolkit for analyzing spatial molecular data."
      homepage: "https://scimap.xyz/"
      documentation: "https://scimap.xyz/All%20Functions/A.%20Pre%20Processing/sm.pp.mcmicro_to_scimap/"
      tool_dev_url: "https://github.com/labsyspharm/scimap"
      licence: "MIT License"
      identifier: biotools:SCIMAP
input:
  # Only when we have meta
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - cellbyfeature: {}
output:
  #Only when we have meta
  - annotedDataCsv:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.csv":
          type: file
          description: Sorted CSV file
          pattern: "*.{csv}"
  - annotedDataH5ad:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.h5ad":
          type: file
          description: Sorted H5AD file
          pattern: "*.{h5ad}"
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@luiskuhn"
maintainers:
  - "@luiskuhn"
