# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "bam_split_by_region"
description: Split the reads in the input bam by specified genomic region.
keywords:
  - split
  - bam
  - sam
  - cram
  - index
components:
  - samtools/view
  - samtools/index

input:
  - ch_bam:
      description: The input channel of this subworkflow containing meta, bam, bai and regions_file
      structure:
        - meta:
            type: map
            description: Groovy Map containing sample information => doesn't have a field called 'genomic_region'
        - bam:
            type: file
            description: BAM/CRAM/SAM file
        - bai:
            type: file
            description: Index for BAM/CRAM/SAM file
        - regions_file:
            type: file
            description: |
              A file containing the genomic regions used to separate the reads in the
              input bam. This should be a BED or TSV file containing either a single
              column of chromosome names, two columns (chromosome name and position),
              or three columns (chromosome name, start position, and end position).
output:
  - bam_bai:
      description: Channel containing a meta map, bam file and index bai file.
      structure:
        - meta:
            type: map
            description: |
              Groovy Map containing sample information
              It contains a new 'genomic_region' field with the included regions
        - bam:
            type: file
            description: BAM/CRAM/SAM file
        - bai:
            type: file
            description: BAM index file
  - versions:
      description: Channel containing software versions
      structure:
        - versions.yml:
            type: file
            description: Files containing software versions
authors:
  - "@TCLamnidis"
maintainers:
  - "@TCLamnidis"
