name: "picard_extractfingerprint"
description: Computes/Extracts the fingerprint genotype likelihoods from the supplied
  file. It is given as a list of PLs at the fingerprinting sites.
keywords:
  - picard
  - extract
  - fingerprint
  - bam
tools:
  - picard:
      description: |
        A set of command line tools (in Java) for manipulating high-throughput sequencing (HTS)
        data and formats such as SAM/BAM/CRAM and VCF.
      homepage: https://broadinstitute.github.io/picard/
      documentation: https://broadinstitute.github.io/picard/
      tool_dev_url: https://github.com/broadinstitute/picard/
      licence: ["MIT"]
      identifier: biotools:picard_tools
input:
  - - meta:
        type: file
        description: |
          Input SAM/BAM/CRAM file
    - bam: {}
    - bai: {}
  - - haplotype_map:
        type: file
        description: |
          A file of haplotype information. The file lists a set of SNPs, optionally arranged in high-LD blocks, to be used for fingerprinting.
          See https://software.broadinstitute.org/gatk/documentation/article?id=9526 for details.
        pattern: "*.{txt,vcf,vcf.gz}"
  - - fasta: {}
  - - fasta_fai: {}
  - - sequence_dictionary: {}
output:
  - vcf:
      - meta: {}
      - "*.vcf.gz": {}
  - tbi:
      - meta: {}
      - "*.vcf.gz.tbi": {}
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@adamrtalbot"
  - "@mauro-saporita"
maintainers:
  - "@adamrtalbot"
  - "@mauro-saporita"
