name: nextclade_run
description: SARS-CoV-2 genome clade assignment, mutation calling, and sequence quality
  checks (C++ implementation)
keywords:
  - nextclade
  - variant
  - consensus
tools:
  - nextclade:
      description: SARS-CoV-2 genome clade assignment, mutation calling, and sequence
        quality checks
      homepage: https://github.com/nextstrain/nextclade
      documentation: https://github.com/nextstrain/nextclade
      tool_dev_url: https://github.com/nextstrain/nextclade
      licence: ["MIT"]
      identifier: biotools:nextclade
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - fasta:
        type: file
        description: FASTA file containing one or more consensus sequences
        pattern: "*.{fasta,fa}"
  - - dataset:
        type: path
        description: Path containing the dataset files obtained by running nextclade
          dataset get
        pattern: "*"
output:
  - csv:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - ${prefix}.csv:
          type: file
          description: CSV file containing nextclade results
          pattern: "*.{csv}"
  - csv_errors:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - ${prefix}.errors.csv: {}
  - csv_insertions:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - ${prefix}.insertions.csv: {}
  - tsv:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - ${prefix}.tsv:
          type: file
          description: TSV file containing nextclade results
          pattern: "*.{tsv}"
  - json:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - ${prefix}.json:
          type: file
          description: JSON file containing nextclade results
          pattern: "*.{json}"
  - json_auspice:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - ${prefix}.auspice.json: {}
  - ndjson:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - ${prefix}.ndjson: {}
  - fasta_aligned:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - ${prefix}.aligned.fasta: {}
  - fasta_translation:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.translation.fasta": {}
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@antunderwood"
  - "@drpatelh"
maintainers:
  - "@antunderwood"
  - "@drpatelh"
