name: "pear"
description: PEAR is an ultrafast, memory-efficient and highly accurate pair-end read
  merger.
keywords:
  - pair-end
  - read
  - merge
tools:
  - "pear":
      description: "paired-end read merger"
      homepage: "https://cme.h-its.org/exelixis/web/software/pear/"
      documentation: "https://cme.h-its.org/exelixis/web/software/pear/doc.html"
      licence: ["Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported"]
      identifier: biotools:pear
input:
  - - meta:
        qualifier: val
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test' ]
    - reads:
        qualifier: path
        type: file
        description: |
          List of input FastQ files with paired-end reads forward and reverse.
output:
  - assembled:
      - meta:
          qualifier: val
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test' ]
      - "*.assembled.fastq.gz":
          qualifier: path
          type: file
          description: FastQ file containing Assembled reads.
          pattern: "*.{fastq.gz}"
  - unassembled:
      - meta:
          qualifier: val
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test' ]
      - "*.unassembled.forward.fastq.gz":
          qualifier: path
          type: file
          description: FastQ files containing Unassembled forward and reverse reads.
          pattern: "*.{fastq.gz}"
      - "*.unassembled.reverse.fastq.gz":
          qualifier: path
          type: file
          description: FastQ files containing Unassembled forward and reverse reads.
          pattern: "*.{fastq.gz}"
  - discarded:
      - meta:
          qualifier: val
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test' ]
      - "*.discarded.fastq.gz":
          qualifier: path
          type: file
          description: FastQ file containing discarded reads.
          pattern: "*.{fastq.gz}"
  - versions:
      - versions.yml:
          qualifier: path
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@mirpedrol"
maintainers:
  - "@mirpedrol"
